In [1]:
import numpy as np

import pandas as pd

In [2]:
df = pd.read_csv('MiningProcess_Flotation_Plant_Database_hour.csv')
df.set_index('date', inplace=True)

In [3]:
df.head(1)

% Iron Feed  % Silica Feed  Starch Flow  Amina Flow  \
date                                                                       
2017-03-10 01:00:00         55.2          16.98  3162.625026  578.786678   

                     Ore Pulp Flow  Ore Pulp pH  Ore Pulp Density  \
date                                                                
2017-03-10 01:00:00     398.753368    10.113487          1.729558   

                     p-Flotation Column 01 Air Flow  \
date                                                  
2017-03-10 01:00:00                      251.166672   

                     p-Flotation Column 02 Air Flow  \
date                                                  
2017-03-10 01:00:00                      250.226086   

                     p-Flotation Column 03 Air Flow  ...  \
date                                                 ...   
2017-03-10 01:00:00                      250.178287  ...   

                     p-Flotation Column 07 Air Flow  \
date                                                  
2017-03-10 01:00:00                      250.208184   

                     p-Flotation Column 01 Level  p-Flotation Column 02 Level  \
date                                                                            
2017-03-10 01:00:00                   450.383776                   446.891845   

                     p-Flotation Column 03 Level  p-Flotation Column 04 Level  \
date                                                                            
2017-03-10 01:00:00                   450.474523                   449.912259   

                     p-Flotation Column 05 Level  p-Flotation Column 06 Level  \
date                                                                            
2017-03-10 01:00:00                   455.792161                    464.38331   

                     p-Flotation Column 07 Level  otp2_% Iron Concentrate  \
date                                                                        
2017-03-10 01:00:00                   450.532747                    66.91   

                     % Silica Concentrate  
date                                       
2017-03-10 01:00:00                  1.31  

[1 rows x 23 columns]

In [4]:
df.columns= [ '% Iron Feed', '% Silica Feed','Starch Flow','Amina Flow','Ore Pulp Flow','Ore Pulp pH','Ore Pulp Density','p-Flotation Column 01 Air Flow','p-Flotation Column 02 Air Flow','p-Flotation Column 03 Air Flow','p-Flotation Column 04 Air Flow','p-Flotation Column 05 Air Flow','p-Flotation Column 06 Air Flow','p-Flotation Column 07 Air Flow','p-Flotation Column 01 Level','p-Flotation Column 02 Level','p-Flotation Column 03 Level','p-Flotation Column 04 Level','p-Flotation Column 05 Level','p-Flotation Column 06 Level','p-Flotation Column 07 Level','% Iron Concentrate','% Silica Concentrate']

In [5]:
df.head(1)

% Iron Feed  % Silica Feed  Starch Flow  Amina Flow  \
date                                                                       
2017-03-10 01:00:00         55.2          16.98  3162.625026  578.786678   

                     Ore Pulp Flow  Ore Pulp pH  Ore Pulp Density  \
date                                                                
2017-03-10 01:00:00     398.753368    10.113487          1.729558   

                     p-Flotation Column 01 Air Flow  \
date                                                  
2017-03-10 01:00:00                      251.166672   

                     p-Flotation Column 02 Air Flow  \
date                                                  
2017-03-10 01:00:00                      250.226086   

                     p-Flotation Column 03 Air Flow  ...  \
date                                                 ...   
2017-03-10 01:00:00                      250.178287  ...   

                     p-Flotation Column 07 Air Flow  \
date                                                  
2017-03-10 01:00:00                      250.208184   

                     p-Flotation Column 01 Level  p-Flotation Column 02 Level  \
date                                                                            
2017-03-10 01:00:00                   450.383776                   446.891845   

                     p-Flotation Column 03 Level  p-Flotation Column 04 Level  \
date                                                                            
2017-03-10 01:00:00                   450.474523                   449.912259   

                     p-Flotation Column 05 Level  p-Flotation Column 06 Level  \
date                                                                            
2017-03-10 01:00:00                   455.792161                    464.38331   

                     p-Flotation Column 07 Level  % Iron Concentrate  \
date                                                                   
2017-03-10 01:00:00                   450.532747               66.91   

                     % Silica Concentrate  
date                                       
2017-03-10 01:00:00                  1.31  

[1 rows x 23 columns]

In [6]:
df = df.drop(['% Silica Concentrate'], axis=1)

In [7]:
Y = df['% Iron Concentrate']
X = df.drop(['% Iron Concentrate'], axis=1)

In [8]:
from sklearn import preprocessing
min_max_scaler = preprocessing.MinMaxScaler()

In [9]:
X_scaled = pd.DataFrame(min_max_scaler.fit_transform(X), columns=X.columns)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.2, random_state=42)

In [11]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
_ = reg.fit(X_train, Y_train)

In [12]:
predictions = reg.predict(X_test)
predictions

array([65.00610867, 64.71610428, 64.05915784, 64.75046131, 65.25222305,
       64.8591417 , 65.32609138, 65.64261261, 65.9337686 , 65.12092752,
       64.93571363, 64.50176628, 64.29898622, 65.18300989, 65.23566371,
       63.60769039, 65.19442852, 64.27682162, 65.03926882, 65.54296698,
       64.75403187, 64.86561842, 65.55482808, 64.9151633 , 64.98264408,
       65.55739789, 64.45699974, 65.12540611, 65.38921961, 65.7876929 ,
       64.62151754, 64.91368198, 65.13740047, 65.17436401, 64.91662162,
       64.88930037, 64.716627  , 65.26943119, 64.34808779, 64.8096182 ,
       65.27881063, 65.06611945, 65.88762995, 65.06391737, 65.03776932,
       63.73362931, 65.28922006, 65.20984196, 65.10416564, 65.03094604,
       64.64166771, 65.04945277, 65.1845571 , 65.15540656, 65.3770036 ,
       65.26383638, 64.41058443, 66.01604218, 65.56872633, 65.06556671,
       63.57531288, 65.39939303, 64.84650708, 65.34490723, 64.28243894,
       65.10888326, 65.4214179 , 64.65529003, 65.81921439, 65.41

In [13]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
error = mean_squared_error(Y_test, predictions)
error

1.0535921496537266

In [14]:
Rsquar = r2_score(Y_test, predictions)
Rsquar

0.14587800365803716

In [15]:
from sklearn.tree import DecisionTreeRegressor
regr_2 = DecisionTreeRegressor(max_depth=5)
regr_2.fit(X_train, Y_train)

DecisionTreeRegressor(max_depth=5)

In [16]:
Y_2 = regr_2.predict(X_test)

In [17]:
Y_2

array([64.41074425, 64.41074425, 64.4380745 , 65.57794437, 66.21855769,
       65.41512356, 65.35322222, 65.24511978, 65.57794437, 64.86800138,
       65.46713681, 64.88616825, 64.4380745 , 64.88616825, 65.41512356,
       64.41074425, 64.86800138, 64.4380745 , 65.24511978, 65.35322222,
       65.46713681, 64.41074425, 64.88616825, 64.88616825, 65.57794437,
       65.73676745, 65.57794437, 64.86800138, 65.57794437, 65.41512356,
       64.88616825, 64.88616825, 64.41074425, 64.41074425, 65.57794437,
       65.15460937, 64.86800138, 65.41512356, 65.57794437, 64.88616825,
       64.84629955, 64.41074425, 65.24511978, 64.86800138, 65.41512356,
       64.41074425, 65.24511978, 64.88616825, 65.3593401 , 64.88616825,
       65.57794437, 65.3593401 , 65.15460937, 65.73676745, 65.24511978,
       65.24511978, 64.88616825, 65.24511978, 66.21855769, 64.88616825,
       64.41074425, 64.88616825, 65.24511978, 65.57794437, 64.41074425,
       64.83062334, 65.41512356, 65.24511978, 65.24511978, 66.21

In [18]:
error2 = mean_squared_error(Y_test, Y_2)
error2

1.1142916330991488

In [19]:
Rsquar = r2_score(Y_test, Y_2)
Rsquar

0.09667038190955579

In [20]:
from sklearn.ensemble import RandomForestRegressor

regressor = RandomForestRegressor(n_estimators=20, random_state=42)
regressor.fit(X_train, Y_train)
Y_pred = regressor.predict(X_test)

In [21]:
Y_pred

array([64.883     , 64.64118351, 63.97847582, 65.47440328, 64.51764704,
       64.71925451, 65.25342961, 65.45268412, 65.18459651, 64.9772445 ,
       65.0135    , 64.65024431, 64.453952  , 64.53492841, 65.2185    ,
       63.199     , 65.0385    , 63.78708422, 64.8465    , 66.136     ,
       64.94332587, 65.4345    , 65.856     , 65.386     , 64.9845    ,
       65.5365    , 65.1085    , 65.15650277, 65.187     , 65.492     ,
       64.81325   , 64.7405    , 64.58648038, 65.06082335, 65.7725    ,
       64.73256142, 64.875     , 65.14943863, 65.1455    , 65.05833525,
       65.34693863, 63.99652885, 65.25175   , 64.85572365, 65.18430652,
       64.00904384, 64.2055    , 65.06407009, 65.138     , 65.63      ,
       66.023     , 64.77769591, 65.39906142, 65.37558717, 64.956     ,
       65.413     , 63.76889315, 65.6245    , 65.9295    , 65.98      ,
       63.0525    , 66.013     , 64.616     , 65.05534743, 64.42466475,
       65.3665    , 65.321     , 65.2805    , 65.8235    , 65.65

In [22]:
error3 = mean_squared_error(Y_test, Y_pred)
error3

0.8990601205281578

In [23]:
from sklearn import metrics

print('Mean Absolute Error:', metrics.mean_absolute_error(Y_test, Y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(Y_test, Y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(Y_test, Y_pred)))

Mean Absolute Error: 0.7432350531004626
Mean Squared Error: 0.8990601205281578
Root Mean Squared Error: 0.9481878086793554


In [24]:
Rsquar = r2_score(Y_test, Y_pred)
Rsquar

0.2711534295036878

In [25]:
from sklearn.ensemble import GradientBoostingRegressor
reg1 = GradientBoostingRegressor()
reg1.fit(X_train, Y_train)
Y_gradient_boosting_pred = reg1.predict(X_test)
Y_gradient_boosting_pred

array([64.85261274, 64.52729874, 64.26568374, 65.17821226, 64.6831048 ,
       65.31548378, 64.79457327, 65.46043049, 65.08121973, 64.97935426,
       65.25281439, 64.95565069, 64.43582465, 64.8799692 , 65.13653433,
       63.32877526, 65.25416069, 64.57410201, 64.77987389, 65.70818931,
       65.14798488, 65.08956961, 65.38229396, 64.68369153, 65.21034658,
       65.33129275, 64.94975357, 65.2285355 , 64.99539154, 65.59411431,
       64.36305661, 64.24892899, 65.00769463, 65.01860266, 65.47797613,
       65.12419873, 64.72809801, 65.46088811, 65.10979741, 64.97260001,
       65.3567247 , 64.68433121, 65.28834867, 64.91215286, 65.35572805,
       63.51910897, 65.03993445, 65.07446715, 65.08559254, 65.06404157,
       65.22027804, 65.46806178, 65.40767983, 65.15923564, 65.09290583,
       65.61048777, 63.81184054, 65.85163078, 65.87354053, 64.93714182,
       63.26174558, 65.20359826, 65.27586624, 65.32647137, 64.24296052,
       65.27546783, 65.41658976, 65.31030784, 65.33244946, 65.41

In [26]:
Rsquar2 = r2_score(Y_test, Y_gradient_boosting_pred)
Rsquar2

0.2669814379538207

In [27]:
from sklearn.ensemble import ExtraTreesRegressor
reg = ExtraTreesRegressor(n_estimators=100, random_state=0).fit(X_train, Y_train)
Y_pred3 = reg.predict(X_test)
Y_pred3

array([64.88717066, 64.22590992, 64.27081463, 65.22061227, 64.79587462,
       64.9956    , 65.09715   , 65.5363    , 64.21816832, 64.79008699,
       65.3093    , 64.57288377, 64.44991332, 65.0086266 , 64.90811227,
       62.9862    , 65.2705    , 64.6553769 , 64.8123    , 66.2209    ,
       65.75401454, 65.1648    , 65.4996    , 65.15997782, 64.99705   ,
       65.24954307, 65.01013051, 65.22820166, 64.8361    , 65.4901    ,
       65.04537527, 64.65840426, 65.07743613, 64.74669015, 65.33829279,
       64.98335   , 64.62827255, 65.7176    , 65.0033    , 65.15015115,
       65.73845   , 63.00414019, 65.3961    , 64.4286009 , 64.88362547,
       63.81334249, 63.98263685, 64.73371228, 65.14294626, 64.86639945,
       65.5298    , 64.64964877, 65.7969    , 65.12438071, 64.7527    ,
       65.78241482, 64.00449274, 65.15595   , 65.5267    , 65.9899    ,
       62.9625    , 66.0022    , 64.913097  , 65.30890807, 64.46835107,
       65.28523773, 65.3605    , 65.4428585 , 65.2891    , 66.02

In [28]:
Rsquar3 = r2_score(Y_test, Y_pred3)
Rsquar3

0.3952641260688511

In [30]:
import xgboost as xgb
xgb_model = xgb.XGBRegressor(objective="reg:linear", random_state=42)
xgb_model.fit(X_train, Y_train)
Y_xgb_pred = xgb_model.predict(X_test)
Y_xgb_pred

[16:21:22] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.
[16:21:23] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.1.0/src/objective/regression_obj.cu:170: reg:linear is now deprecated in favor of reg:squarederror.


array([65.19225 , 64.502815, 65.825905, 64.780525, 64.49947 , 65.41847 ,
       65.108925, 65.32274 , 64.92294 , 64.78455 , 65.260864, 64.9845  ,
       64.81985 , 64.78062 , 64.90063 , 63.316433, 65.542786, 64.316895,
       65.0339  , 66.17836 , 64.8963  , 64.90622 , 65.79614 , 65.56548 ,
       65.14401 , 65.96715 , 65.222626, 65.47822 , 64.84616 , 65.35562 ,
       64.50034 , 65.3188  , 65.117256, 64.26361 , 65.34656 , 65.15979 ,
       64.51801 , 65.87332 , 65.59225 , 65.07443 , 65.527985, 63.08078 ,
       65.422905, 64.64153 , 65.15801 , 63.63999 , 64.08395 , 63.82906 ,
       64.791824, 65.18032 , 65.99688 , 65.29446 , 65.64579 , 65.05597 ,
       64.4466  , 65.758965, 64.45685 , 65.171295, 65.141754, 65.186325,
       62.772465, 65.66775 , 65.2999  , 66.417366, 64.7189  , 64.38777 ,
       65.190315, 65.568886, 65.94818 , 65.81559 , 65.42438 , 64.65563 ,
       63.796032, 64.197136, 64.91255 , 65.92337 , 65.03022 , 65.237595,
       65.90118 , 64.609245, 65.058975, 65.28416 , 

In [31]:
Rsquar3 = r2_score(Y_test, Y_xgb_pred)
Rsquar3

0.25402556917434127

In [38]:
embed_dim = 128
lstm_out = 200
batch_size = 32
from keras.models import Sequential
import tensorflow
from keras.layers import Embedding
from keras.layers.recurrent import LSTM
from keras.layers.core import Dense
model = Sequential()
model.add(Embedding(2500, embed_dim,input_length = X.shape[1], dropout = 0.2))
model.add(LSTM(lstm_out, dropout_U = 0.2, dropout_W = 0.2))
model.add(Dense(2,activation='softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer='adam',metrics = ['accuracy'])
print(model.summary())

<ipython-input-38-aaa942982a43>:10: UserWarning: The `dropout` argument is no longer support in `Embedding`. You can apply a `keras.layers.SpatialDropout1D` layer right after the `Embedding` layer to get the same behavior.
  model.add(Embedding(2500, embed_dim,input_length = X.shape[1], dropout = 0.2))
<ipython-input-38-aaa942982a43>:11: UserWarning: Update your `LSTM` call to the Keras 2 API: `LSTM(200, dropout=0.2, recurrent_dropout=0.2)`
  model.add(LSTM(lstm_out, dropout_U = 0.2, dropout_W = 0.2))


Model: "sequential_5"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, 21, 128)           320000    
_________________________________________________________________
lstm_2 (LSTM)                (None, 200)               263200    
_________________________________________________________________
dense_1 (Dense)              (None, 2)                 402       
Total params: 583,602
Trainable params: 583,602
Non-trainable params: 0
_________________________________________________________________
None


In [39]:
model.fit(X_train, Y_train, batch_size =batch_size, nb_epoch = 1,  verbose = 5)

<ipython-input-39-4777ca680707>:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  model.fit(X_train, Y_train, batch_size =batch_size, nb_epoch = 1,  verbose = 5)


ValueError: Error when checking target: expected dense_1 to have shape (2,) but got array with shape (1,)

In [ ]:
score,acc = model.evaluate(x_test,y_test,verbose=2,batch_size=batch_size)
print("score:%.2f "%(score))
print("Validation Accuracy:%.2f "%(acc))